defaults:
  - experiment: extract.rent
  - override /dataset: maidavale
  - _self_

paths:
  smir: /raid/datasets/Maida_Vale_IR_Database/MV4/AS2/Eigenmike Capsules/
  anechoic: /raid/projects/mmi599-pareto_fit/higrid/data/sdata/anechoic/

run_name: ${now:%Y-%m-%d_%H-%M-%S}

hydra:
  job:
    chdir: True
  run:
    dir: outputs/${_name_}/${dataset._name_}-${dataset.mic}/${analyse.room}/${run_name}

resume: True
n_threads: 4
save: False
